version: '3'
services:
   etl:
      build: .
      depends_on:
         - postgres
      links:
         - postgres
      environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
   postgres:
      image: postgres:11
      restart: always
      ports:
         - 5432:5432
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: password
         POSTGRES_DB: database
