BEGIN;

DROP SCHEMA IF EXISTS landing_performance CASCADE;
CREATE SCHEMA IF NOT EXISTS landing_performance;

DROP SCHEMA IF EXISTS bip_performance CASCADE;
CREATE SCHEMA IF NOT EXISTS bip_performance;

COMMIT;